project:
  type: website

website:
  title: "How to GDCP-Jahrestagung"
  navbar:
    background: "#ff6900"
    right:
      - text: FAQ
        href: blog.qmd
      - icon: globe
        text: GDCP-Website
        href: https://gdcp-ev.de/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

